name: vizeo_theme
description: Vizeo Theme
version: 0.0.8
publish_to: 'none'
homepage: https://github.com/VIZEODEV/eu_vizeo_flutter_vizeotheme

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get:

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  lint:


flutter:
  fonts:
    - family: Icons_App
      fonts:
        - asset: assets/fonts/Icons_App.ttf
    - family: DIN2014
      fonts:
        - asset: assets/fonts/DIN2014-Regular.ttf
